server:
  port: 80
  context-path: /
  session:
    timeout: 3600

spring:
  datasource:
    url:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 2
      max-idle: 10
      max-active: 20
      max-wait: 200
      test-on-borrow: true
  session:
    store-type: none

logging:
  level:
    root: INFO
    com.ucsmy.ucas: DEBUG

# 序列号生成器配置，格式：4位前缀 + 8位日期 + 6位流水号，限制长度必须为18位，目前长度不支持配置
serialNumber:
  # 是否开启:true;false
  open: true
  # 生成模式：db；redis; default(乱序模式)
  mode: redis
  # 序列号默认前缀
  prefix: 1000
  # 序列号备用前缀，当出现重复主键时使用备用序列号生成器生成
  backupPrefix: 9900
  # 序列号编号格式
  numberPattern: "000000"
  # 序列号日期格式
  datePattern: yyMMddHH
  # db模式线程最大等待时间，毫秒
  waitTime: 10000
  # 序列号起始基数
  startNum: 1
